### ISSUE TITLE
how to use the Iou-Net in the work

### ISSUE THREAD

**Issue by maggiequan** [vacancy/PreciseRoIPooling#10]
hi，想请问输入图像首先被馈送到FPN骨干网提取特征，然后分别送到PrRoI pooling和RPN网络。在RPN网络中提取bbox和faster rcnn中一样的吗？PrRoI pooling是对bbox的优化调整？PrRoI pooling之后的7*7*256那是？fc后面的分支就是nms以及分类回归吗？

**Comment by vacancy** [comment]
Q: 在RPN网络中提取bbox和faster rcnn中一样的吗？
A: 一样。
Q: PrRoI pooling是对bbox的优化调整？
A: 关于refine bbox，请参见Algo. 2.
Q: PrRoI pooling之后的77256那是？
A: PrRoI Pooling得到的feature，和Faster RCNN一样。
Q: fc后面的分支就是nms以及分类回归吗？
A: 是。

**Comment by maggiequan** [comment]
谢谢您的回答，我是不是只需要在Faster R-CNN+FPN的结构中将传统的pooling替换为PrRoI pooling，以及使用iou作为nms的排名依据就可以了。

**Comment by maggiequan** [comment]
> Q: 在RPN网络中提取bbox和faster rcnn中一样的吗？
> A: 一样。
> Q: PrRoI pooling是对bbox的优化调整？
> A: 关于refine bbox，请参见Algo. 2.
> Q: PrRoI pooling之后的77256那是？
> A: PrRoI Pooling得到的feature，和Faster RCNN一样。
> Q: fc后面的分支就是nms以及分类回归吗？
> A: 是。

对于fc后面的分支nms是新增加一个使用iou作为nms依据？还是说就是修改faster-rcnn里的分类置信度为iou的？我看论文中有说在iou作为nms依据的基础上做分类置信度的？如果是这样的话，那是？

**Comment by vacancy** [comment]
关于IoU-guided NMS，具体内容请参见我们论文的Algo 2. 大致来说，当两个box的重合度>阈值（比如0.5），删除IoU Confidence较低的，对于剩下的Box的分类置信度=max(两个box的分类置信度)
