### ISSUE TITLE
Questions about IOU-Net

### ISSUE THREAD

**Issue by SingL3** [vacancy/PreciseRoIPooling#11]
Hello! I am very interesting in this work. After reading the paper, I have several questions.
Firstly, the IOU head need label to regress, but the IOU and the final cls_score and bbox_reg are forwarded at the same time. So did you use the IOU between the RPN proposal and the groundtruth as the label of the IOU head?
Secondly, at the refinement part, do you actually update the weight of the network or just try if the network will be better or tolerant after backward but didn't actually update it?

**Comment by lycqu** [comment]
I have the same questions with you ?May I comnunicate teh problems with you on wechat.MY wechat ID:18827384395. Three Question:(1)IOU loss (2)IOU label (3)the  relationshape between  the IOU loss  and localization confidience.

**Comment by SingL3** [comment]
I reread the training of IOU part. And here is my thinking about the first question I asked. Would you please see that whether I am right?
The gt of the IOU branch is a sampling the augmenting of gt boxes. When training the whole network end-to-end, the proposal of RPN is pooled and fed into and then the cls bbox branch but not the IOU branch. And the augmentation of boxes is pooled and fed into both the cls bbox branch and IOU branch.
I will appreciate it if you reply me.
And I am still confused with the second question.

**Comment by YuningJiang** [comment]
To the first question, yes.
To the second question, the weights of network will NOT be updated during the refinement step. You can put it in this way: _IoU = f(bbox, w)_, where _f(.)_ is the trained network to predict _IoU_, _bbox_ is the box proposal and _w_ are the weights of network. In the refinement step, we update _bbox_ instead of _w_ to maximize IoU.

**Comment by SingL3** [comment]
@YuningJiang

**Comment by l2009312042** [comment]
good answer  help me  a lot
