### ISSUE TITLE
complie error 

### ISSUE THREAD

**Issue by lichuang0529** [vacancy/PreciseRoIPooling#13]
when I run the ./ travis.sh, I got the error:

Working directory:  /media/t1/0a33a0a0-b876-45c1-bb1c-f0d6fecc3bf9/cascade/bin/cascade-rcnn_Pytorch/lib/model/pr_roi_pooling/pytorch/prroi_pool/src
Compiling prroi_pooling kernels by nvcc...
Working directory:  /media/t1/0a33a0a0-b876-45c1-bb1c-f0d6fecc3bf9/cascade/bin/cascade-rcnn_Pytorch/lib/model/pr_roi_pooling/pytorch/prroi_pool
Building python libraries...
Traceback (most recent call last):
  File "build.py", line 13, in <module>
    import torch
ImportError: No module named 'torch'
But I think  pytorch is installed correctly.Could you help me?
@vacancy Thank you~

**Comment by vacancy** [comment]
Hi, @lichuang0529 What's the version of Python you are using? In `travis.sh`, I assumed that you are using python3. Please check the script for details.

**Comment by lichuang0529** [comment]
> Hi, @lichuang0529 What's the version of Python you are using? In `travis.sh`, I assumed that you are using python3. Please check the script for details.



> Hi, @lichuang0529 What's the version of Python you are using? In `travis.sh`, I assumed that you are using python3. Please check the script for details.

Thank you very much
