### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by rainofmine** [vacancy/PreciseRoIPooling#2]
when I run ./travis.sh, I got an error.

Compiling prroi_pooling kernels by nvcc...
prroi_pooling_gpu_impl.cu(1): error: expected a declaration
1 error detected in the compilation of "/tmp/tmpxft_00009600_000000007_prroi_pooling_gpu_impl.cpp1.ii".

Could anyone help me ?

**Comment by vacancy** [comment]
Hi @rainofmine . Can you provide more details about this, such as your machine configuration?

**Comment by vacancy** [comment]
Closing the thread as there is no response. Please re-open it if there is any update.

**Comment by AHUgaoyuan** [comment]
> when I run ./travis.sh, I got an error.
> 
> Compiling prroi_pooling kernels by nvcc...
> prroi_pooling_gpu_impl.cu(1): error: expected a declaration
> 1 error detected in the compilation of "/tmp/tmpxft_00009600_000000007_prroi_pooling_gpu_impl.cpp1.ii".
> 
> Could anyone help me ?

 have the same problem. Have you solved your problem?

**Comment by klyjb** [comment]
@AHUgaoyuan Hello,I met the same error,have you solved the problem yet?Thank you.

**Comment by AHUgaoyuan** [comment]
> @AHUgaoyuan Hello,I met the same error,have you solved the problem yet?Thank you.

Yes, I've worked it out.You should use git instead of downloading.

**Comment by topriss** [comment]
suggest a hint in README:
please use use git clone instead of downloading, 
otherwise softlinks will have unexpacted behaviour
./pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu*

**Comment by vacancy** [comment]
@topriss Thank you for the suggestion. Just added.

**Comment by noticeable** [comment]
meet the same problem,have anybody solved problem yet?

**Comment by vacancy** [comment]
Use `git clone` instead of zip download.
