### ISSUE TITLE
I have successfully emply in my 2080ti,here some advice .

### ISSUE THREAD

**Issue by DeepBrainsMe** [vacancy/PreciseRoIPooling#24]
0: use conda create a new envirment 
1: Please use pip install packages  instead of conda 
2: You'd better install cuda10 in your ubuntu  and use " pip " to install pytorch1.0 
3: Don't use conda install cudatoolkit and cudnn.

**Comment by Hevans123** [comment]
Hi, @DeepBrainsMe. I can't compile it when I tried with Cuda 9.0 .Does Cuda version really matters?

**Comment by DeepBrainsMe** [comment]
Sometimes it is.
If your gpu is  20series ，cuda10 is needed.
发自我的iPhone

------------------ Original ------------------

**Comment by Hevans123** [comment]
Hi, @DeepBrainsMe  I use Cuda10 and pytorch 1.0.1(use pip to install）,but I still can't compile it. Is there any other things should I focus on? Thanks a lot.
At the end, it says:
[3/3] c++ prroi_pooling_gpu.o prroi_pooling_gpu_impl.cuda.o -shared -L/usr/local/cuda/lib64 -lcudart -o _prroi_pooling.so
Loading extension module _prroi_pooling...
Can not compile Precise RoI Pooling library.
Done

**Comment by Hevans123** [comment]
I solved the problem.Thanks

**Comment by zhu2014yi** [comment]
> Hi, @DeepBrainsMe I use Cuda10 and pytorch 1.0.1(use pip to install）,but I still can't compile it. Is there any other things should I focus on? Thanks a lot.
> At the end, it says:
> [3/3] c++ prroi_pooling_gpu.o prroi_pooling_gpu_impl.cuda.o -shared -L/usr/local/cuda/lib64 -lcudart -o _prroi_pooling.so
> Loading extension module _prroi_pooling...
> Can not compile Precise RoI Pooling library.
> Done

hi,how do you solve it,i meet the same problem.
