### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by AHUgaoyuan** [vacancy/PreciseRoIPooling#25]
When I tried to run 'travis.sh' to compile the file, I encountered the following errors. My environment is Ubuntu 16.04, cuda9.0, compiled using python2.This problem has troubled me for a few days. May I ask how to solve it? I really hope to get your help, thank you!
--------------------------------------------------------------------------------------------------------------------
`prroi_pooling_gpu_impl.cu(1): error: expected a declaration

1 error detected in the compilation of "/tmp/tmpxft_00002a4b_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".

/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected identifier or ‘(’ before ‘.’ token
 ../../../src/prroi_pooling_gpu_impl.cuh

/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:19:47: error: ‘state’ undeclared (first use in this function)
     const float *data_ptr = THCudaTensor_data(state, features);

PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:44:47: error: ‘state’ undeclared (first use in this function)
     const float *data_ptr = THCudaTensor_data(state, features);

/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:73:47: error: ‘state’ undeclared (first use in this function)
     const float *data_ptr = THCudaTensor_data(state, features);

raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by vacancy** [comment]
What's your PyTorch version? It seems that you are using the pytorch0.4 branch.

**Comment by AHUgaoyuan** [comment]
> What's your PyTorch version? It seems that you are using the pytorch0.4 branch.

Thank you for replying to my message. My version of pytorch is 0.4.0, using your branch code of 0.4.

**Comment by AHUgaoyuan** [comment]
I added the following code in travis.sh。but it didn't work for me.
--------------------------------------------------------------------------------------------------------------------
`export CUDA_PATH=/usr/local/cuda-9.0/
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export CPATH=/usr/local/cuda-9.0/include${CPATH:+:${CPATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
#You may also want to ad the following
#export C_INCLUDE_PATH=/opt/cuda/include

export CXXFLAGS="-std=c++11"
export CFLAGS="-std=c99"`

**Comment by vacancy** [comment]
Have you made any change to the code? 
https://github.com/vacancy/PreciseRoIPooling/blob/pytorch0.4/pytorch/prroi_pool/src/prroi_pooling_gpu.c#L16
We have defined the symbol `state` here.

Also... The file content:
```
/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected identifier or ‘(’ before ‘.’ token
../../../src/prroi_pooling_gpu_impl.cuh
```
looks weird to me.

**Comment by AHUgaoyuan** [comment]
> Have you made any change to the code?
> https://github.com/vacancy/PreciseRoIPooling/blob/pytorch0.4/pytorch/prroi_pool/src/prroi_pooling_gpu.c#L16
> We have defined the symbol `state` here.
> 
> Also... The file content:
> 
> ```
> /PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected identifier or ‘(’ before ‘.’ token
> ../../../src/prroi_pooling_gpu_impl.cuh
> ```
> 
> looks weird to me.
------------------------------------------------------------------------------------------------------------------
 didn't make any changes to the original code, but the version I downloaded earlier doesn't have prroi_pooling_gpu_impl.cu and prroi_pooling_gpu_impl.cuh files in the src folder.But I currently have these two files in the version I need to compile.

**Comment by AHUgaoyuan** [comment]
Does anyone else have this problem?

**Comment by Hevans123** [comment]
@AHUgaoyuan ,try to use git clone the repository. Simply download will cause problem.
Simply download 'prroi_pooling_gpu_impl.cuh' will be like this "../../../src/prroi_pooling_gpu_impl.cuh"
Actually it's not like this

**Comment by AHUgaoyuan** [comment]
> @AHUgaoyuan ,try to use git clone the repository. Simply download will cause problem.
> Simply download 'prroi_pooling_gpu_impl.cuh' will be like this "../../../src/prroi_pooling_gpu_impl.cuh"
> Actually it's not like this

-------------------------------------------------------------------------------------------------------------------- 
 Yes, it is indeed for this reason, which is useful to me, thank you very much!

**Comment by vacancy** [comment]
Thanks, @Hevans123 Best luck @AHUgaoyuan
