### ISSUE TITLE
Couldn't find ./travis.sh in guided directory

### ISSUE THREAD

**Issue by 19940312** [vacancy/PreciseRoIPooling#27]
Sorry to bother you, I encounter a fatal problem that I couldn't find travis.sh in guided directory, could u send it to me, my email is ls1425854658@163.com, thx.

**Comment by vacancy** [comment]
The master/pytorch1.0 branch does not use ./travis.sh.
The pytorch0.4 branch uses ./travis.sh, it could be found here:
https://github.com/vacancy/PreciseRoIPooling/blob/pytorch0.4/pytorch/prroi_pool/travis.sh
