### ISSUE TITLE
pytorch1.0, python2.7, how to import / compile it?

### ISSUE THREAD

**Issue by haochange** [vacancy/PreciseRoIPooling#29]
the error is:
raise ImportError('Can not compile Precise RoI Pooling library.')

**Comment by Solomon1588** [comment]
If you meet error 'expected unqualified-id before .' token , you can try to replace prroi_xxx_impl.cu and prroi_xxx_impl.cuh with the same name source code from ../../../src. Then you can compiled _prroi_pooling successfully. Hope can help you :D
