### ISSUE TITLE
Question about Optimization-based bounding box refinement

### ISSUE THREAD

**Issue by dingjiansw101** [vacancy/PreciseRoIPooling#3]
Hi, I think the Optimization-based bounding box refinement is very interesting. But I have a question. What is the meaning of  "scale(grad, bj)" in the Optimization-based bounding box refinement? Do you have plan to share the code of it ?

**Comment by vacancy** [comment]
We described it at the end of that section.

```
In the implementation, shown in Algorithm 2 Line 6, we manually scale up
the gradient w.r.t. the coordinates with the size of the bounding box on that
axis (e.g., we scale up nabla x1 with width(bj)). This is equivalent to perform the
optimization in log-scaled coordinates (x/w, y/h, log w, log h) as in [5]. We also
employ a one-step bounding box regression for an initialization of the coordinates.
```

**Comment by dingjiansw101** [comment]
I have seen it. But I am still not sure what the specific expression of the scale function is.

**Comment by vacancy** [comment]
Scale means “multiplication”. For example,
x1 = x1 + learningrate * width * grad(x1)

Sorry for the formatting issue as I am writing this on my cellphone.

**Comment by vacancy** [comment]
Closing the issue for now. Feel free to reopen it if there are any further questions.
