### ISSUE TITLE
Running on different GPU in mulitple processes

### ISSUE THREAD

**Issue by shuida** [vacancy/PreciseRoIPooling#33]
Hello,  @vacancy thanks for your great work.
Can PreciseRoIPooling run on different GPU in mulitple processes?
It seems that PreciseRoIPooling run on current gpu by default, resulting in slow speed when in multiple processes.

**Comment by vacancy** [comment]
Definitely you can do that. I think the only thing you need to be careful is that PrRoIPooling takes batch index as its input, so it's a bit tricky if you have a list of bboxes from the data loader and want to split them onto different GPUs.

**Comment by vacancy** [comment]
--- If your point is to configure different sub-processes to use different GPUs, simply use model.to(torch.device('cuda:0')). See detailed tutorial at https://pytorch.org/docs/stable/notes/cuda.html
