### ISSUE TITLE
你好，原论文当中提到了在cascade rcnn当中进行测试，效果有一些提升

### ISSUE THREAD

**Issue by gittigxuy** [vacancy/PreciseRoIPooling#4]
请问你们是用哪个版本的cascade rcnn呢？是https://github.com/guoruoqian/cascade-rcnn_Pytorch
这个版本的rcnn吗？
请问使用你们这个repo之后coco2014以及voc2007的AP75的结果是多少呢？谢谢了

**Comment by vacancy** [comment]
Thank you for interest in our paper and this implementation. Please also note that this is NOT the full implementation of the paper.

The result on Cascade RCNN is based on the official implementation: https://github.com/zhaoweicai/cascade-rcnn .

Also, quoted from the paper:

```
To validate the proposed methods, in both Section 4.1 and
4.2, a standalone IoU-Net (without R-CNN modules) is trained separately with
the object detectors. IoU-guided NMS and optimization-based bounding box
refinement, powered by the IoU-Net, are applied to the detection results.
```

The results on the paper regarding the Cascade RCNN is based on the minival split (e.g., see https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/README.md). We did not conduct experiments on the VOC dataset.

**Comment by hongdayu** [comment]
> 请问你们是用哪个版本的cascade rcnn呢？是https://github.com/guoruoqian/cascade-rcnn_Pytorch
> 这个版本的rcnn吗？
> 请问使用你们这个repo之后coco2014以及voc2007的AP75的结果是多少呢？谢谢了

我用了guoruoqian的版本，但效果没提升

**Comment by vacancy** [comment]
Based on our experiments, directly substituting RoI Align with Pr RoI Pooling will not bring performance improvement. We use Pr RoI Pooling more because of its continuity in gradient. Please see the paper for more details.

I am closing the issue for now. Feel free to open it again if you have further concerns.
