### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by FightingZhen** [vacancy/PreciseRoIPooling#40]
Hello!
I have used your PrPool model into my own framework.
I used a pre-trained resnet-50 to extract features from one image, follwed by feeding into PrPool model to generate a vector with size (1, 1, 1024, 1).
Another image is also fed into the pre-trained network to extract features, followed by a GAP layer to generate another vector with the same size.
The two vectors are then calculated with MSE loss, which is utilized to back-propogate for the gradients of ROI index.
However, when I run the program, an error: '**RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED**' occured, can you help me to fix this problem? thank you ~

**Comment by xiuruisi** [comment]
@FightingZhen ， Hi,  I also meet the problem,  have you solved it？
