### ISSUE TITLE
Gradients for bounding box refinement

### ISSUE THREAD

**Issue by AlexanderHustinx** [vacancy/PreciseRoIPooling#41]
Dear authors,

I have a question regarding Algorithm 2: Optimization-based bounding box refinement.
In Algorithm 2 you set `**grad** <- \nabla_{b_j} IoU(PrPool(F, b_j))`
Later you also mention: "... the proposed PreciseRoI Pooling layer enables the computation of the gradient of IoU w.r.t. bounding box coordinates."

- How do you get these gradient values, **grad** (in PyTorch)?

Thanks in advance!

**Comment by vacancy** [comment]
1. Compute IoU in PyTorch, denote the tensor as `iou`.
2. Run `iou.backward()`
3. The gradients are `b_j.grad`.
