### ISSUE TITLE
there is no `./travis.sh`

### ISSUE THREAD

**Issue by yxy1995123** [vacancy/PreciseRoIPooling#44]
I couldn't find `./travis.sh` in pytorch/prroi_pool file

**Comment by vacancy** [comment]
If you are using PyTorch 0.4, use the pytorch0.4 branch.
For PyTorch 1.0, you don't need the ./travis.sh file.

**Comment by kuiran** [comment]
> If you are using PyTorch 0.4, use the pytorch0.4 branch.
> For PyTorch 1.0, you don't need the ./travis.sh file.

I dom.t know waht means pytorch0.4 branch.How could i get the pytorch0.4 version
