### ISSUE TITLE
Building extension module _prroi_pooling... ninja: error: unknown target '–v'

### ISSUE THREAD

**Issue by 1032697379** [vacancy/PreciseRoIPooling#46]
您好，我将它用在MaskRCNN官方公布的代码中出现一下问题
我的环境配置：
2020-02-13 17:32:54,111 maskrcnn_benchmark INFO: 
PyTorch version: 1.0.0.dev20190328
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.56
cuDNN version: Could not collect
我运行后出现的问题
2020-02-13 17:33:11,894 maskrcnn_benchmark.trainer INFO: Start training
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
ninja: error: unknown target '–v'
Traceback (most recent call last):
  File "/home/syx/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 950, in _build_extension_module
    check=True)
  File "/home/syx/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '–v']' returned non-zero exit status 1.

**Comment by chrisway613** [comment]
> Command '['ninja', '–v']' returned non-zero exit status 1.

解决了么 我的异常里也有：Command '['ninja', '–v']' returned non-zero exit status 1.这个
求指教

**Comment by vacancy** [comment]
It looks like an issue caused by the mismatch between PyTorch and ninja versions. This has nothing to do with this repo. Maybe try to modify the source code of PyTorch and remove the "-v" argument when emitting ninja.
