### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by chrisway613** [vacancy/PreciseRoIPooling#47]
When I run as below:

 from prroi_pool import PrRoIPool2D

 avg_pool = PrRoIPool2D(window_height, window_width, spatial_scale)
 roi_features = avg_pool(features, rois)
------------------------------------------------------------------------------

I got the error:
 Using /tmp/torch_extensions as PyTorch extensions root...
 Detected CUDA files, patching ldflags
 Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja... 
 Building extension module _prroi_pooling...

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py in _build_extension_module(name, build_directory, verbose)
   1029                 cwd=build_directory,
-> 1030                 check=True)
   1031         else:

/usr/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    437             raise CalledProcessError(retcode, process.args,
--> 438                                      output=stdout, stderr=stderr)
    439     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-6-6d1e074bff93> in <module>
      1 avg_pool = PrRoIPool2D(window_height, window_width, spatial_scale)
----> 2 roi_features = avg_pool(features, rois)
      3 roi_features.shape

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/private/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py in forward(self, features, rois)
     26 
     27     def forward(self, features, rois):
---> 28         return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
     29 
     30     def extra_repr(self):

~/private/PreciseRoIPooling/pytorch/prroi_pool/functional.py in forward(ctx, features, rois, pooled_height, pooled_width, spatial_scale)
     43     @staticmethod
     44     def forward(ctx, features, rois, pooled_height, pooled_width, spatial_scale):
---> 45         _prroi_pooling = _import_prroi_pooling()
     46 
     47         assert 'FloatTensor' in features.type() and 'FloatTensor' in rois.type(), \

~/private/PreciseRoIPooling/pytorch/prroi_pool/functional.py in _import_prroi_pooling()
     31                 '_prroi_pooling',
     32                 [pjoin(root_dir, 'prroi_pooling_gpu.c'), pjoin(root_dir, 'prroi_pooling_gpu_impl.cu')],
---> 33                 verbose=True
     34             )
     35         except ImportError as e:

/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py in load(name, sources, extra_cflags, extra_cuda_cflags, extra_ldflags, extra_include_paths, build_directory, verbose, with_cuda, is_python_module)
    659         verbose,
    660         with_cuda,
--> 661         is_python_module)
    662 
    663 

/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py in _jit_compile(name, sources, extra_cflags, extra_cuda_cflags, extra_ldflags, extra_include_paths, build_directory, verbose, with_cuda, is_python_module)
    828                     build_directory=build_directory,
    829                     verbose=verbose,
--> 830                     with_cuda=with_cuda)
    831             finally:
    832                 baton.release()

/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py in _write_ninja_file_and_build(name, sources, extra_cflags, extra_cuda_cflags, extra_ldflags, extra_include_paths, build_directory, verbose, with_cuda)
    881     if verbose:
    882         print('Building extension module {}...'.format(name))
--> 883     _build_extension_module(name, build_directory, verbose)
    884 
    885 

/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py in _build_extension_module(name, build_directory, verbose)
   1041         if hasattr(error, 'output') and error.output:
   1042             message += ": {}".format(error.output.decode())
-> 1043         raise RuntimeError(message)
   1044 
   1045 

RuntimeError: Error building extension '_prroi_pooling'

So, what's the problem?

**Comment by ecd1012** [comment]
I'm getting the same error. What version of PyTorch are you using?

**Comment by vacancy** [comment]
For compilation errors, please provide the detailed output of the `ninja -v` command.

**Comment by chrisway613** [comment]
> I'm getting the same error. What version of PyTorch are you using?

1.3

**Comment by chrisway613** [comment]
> ninja -v

Run this command with which file?
I see we don't need the build file when using pytorch > 0.4
If I run this command directly, it reminds me as below:
 ninja: error: loading 'build.ninja': No such file or directory

**Comment by vacancy** [comment]
For example, when you load the module, it will print the following lines to the terminal:

```
Using /tmp/torch_extensions as PyTorch extensions root...
Creating extension directory /tmp/torch_extensions/_prroi_pooling...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
[1/3] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem <mydirectory>/anaconda/envs/torch1.2/lib/python3.7/site-packages/torch/include -isystem <mydirectory>/anaconda/envs/torch1.2/lib/python3.7/site-packages/torch/include/torch/cs
rc/api/include -isystem <mydirectory>/anaconda/envs/torch1.2/lib/python3.7/site-packages/torch/include/TH -isystem <mydirectory>/anaconda/envs/torch1.2/lib/python3.7/site-packages/torch/include/THC -isystem <mydirectory>/anaconda/envs/torch1.2/include/
python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++11 -c <mydirectory>/projects/Jacinle/vendors/PreciseRoIPooling/pytorch/p
rroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
............ (more lines)
```

Please completely copy the lines and paste them here so that we can locate the error.

Also, you can also find the raw cuda and ninja build files in the directory shown on the screen. In my case, it's `/tmp/torch_extensions/_prroi_pooling`. If you go to this directory and enter `ninja -v` you can see more clearly where the building errors are.

**Comment by zzzmm1** [comment]
[1/3] /usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
FAILED: prroi_pooling_gpu_impl.cuda.o
/usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
/home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu(1): error: expected a declaration

1 error detected in the compilation of "/tmp/tmpxft_00001f50_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
In file included from /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:19:0:
/home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected unqualified-id before ‘.’ token
 ../../../src/prroi_pooling_gpu_impl.cuh
 ^
ninja: build stopped: subcommand failed.


Could you give me some help? @vacancy 
My environment is  2080ti pytorch1.1.0 cuda10.0

**Comment by vacancy** [comment]
Please fully clone the repo. Do NOT use the github zip feature. It will break symbol links.

**Comment by bebebe666** [comment]
> [1/3] /usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
> FAILED: prroi_pooling_gpu_impl.cuda.o
> /usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
> /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu(1): error: expected a declaration
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00001f50_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".
> [2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
> FAILED: prroi_pooling_gpu.o
> c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/TH -isystem /home/jyj/anaconda3/envs/TracKit/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /home/jyj/anaconda3/envs/TracKit/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
> In file included from /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:19:0:
> /home/jyj/TracKit/lib/models/online/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected unqualified-id before ‘.’ token
> ../../../src/prroi_pooling_gpu_impl.cuh
> ^
> ninja: build stopped: subcommand failed.
> 
> Could you give me some help? @vacancy
> My environment is 2080ti pytorch1.1.0 cuda10.0

I meet the same quesstion, how do you solve it

**Comment by bebebe666** [comment]
I meet the same question How do you solve it? @zzzmm1
