### ISSUE TITLE
Runing Time of PreciseRoIPooling

### ISSUE THREAD

**Issue by SherlockHolmes221** [vacancy/PreciseRoIPooling#49]
Faster than ROIAlign?

**Comment by vacancy** [comment]
Haven't tested seriously. My intuition is that they should run similarly fast. Maybe the RoIAlign is a bit faster, considering it samples 4 points in each box.

**Comment by kun-dragon** [comment]
PrRool use integral to compute the value. In computer, calculating the integral also needs to  sample some points. So I think that question depends on the number of sampling points of the integral. And if the accuracy of the integral is fixed, I think that the number is larger than 4 for large ROI and fewer than for small ROI.
