### ISSUE TITLE
What are the target of the IoU-Net branch?

### ISSUE THREAD

**Issue by zhoulukuan** [vacancy/PreciseRoIPooling#5]
Hi, thanks for your great work. I come here to try to find some answers about paper by reading code. However, it's not a full implementation. So I am asking here and hope that it will not cause trouble. 
1. What are the target of the IoU-Net branch during training? The IoU between RoIs and ground truth or others? Besides, Algorithm 2, bounding box refinement shows that we need to compute grad to update detected box. But we have no labels when we used this algorithm during inference. So you set the targets to 1 to make the detected box more precise?
2. You said: We generate bounding boxes and labels for training the IoU-Net by augmenting the groundtruth, instead of taking proposals from RPNs. When I want to agument data, I tend to randomly change pictures, for example, fliping or rotation. I have no idea what's your meaning, could you give me some advice?

Thanks for you.

**Comment by vacancy** [comment]
Thank you for your interest in our work!

A1: Yes. Your understanding is correct. During training, the IoU-Net learns to predict the IoU between RoIs and the groundtruth. During testing, we use the optimization-based algorithm (Algo 2) to maximize this IoU. (You can view this as setting the target to be IoU=1)

A2: "Augmenting the groundtruth" here means jittering the groundtruth bounding box to get some "not-perfectly-localized bounding boxes". We use such "synthesized" RoIs to train the IoU predictor. Here, jittering is performed by adding noise to the box coordinates.

**Comment by w86742756** [comment]
很有启发性,可以把代码放出来学习一下吗?
多谢

**Comment by zzdang** [comment]
请问rcnn的iou分支中,论文中iou label的取值范围是[-1,1]. 
[0,1]是指前景的roi与gt的iou, [-1,0]是指背景的roi与gt的roi吗?

**Comment by vacancy** [comment]
@zzdang It depends on your threshold for labeling RoIs. Usually we treat RoIs with IoU > 0.5 as positive samples. In such case, the answer is Yes.

**Comment by tpys** [comment]
@vacancy 请问大神，这个(-1~1)的normalize 是怎么做的呢？ 根据每轮match到的IOU的最大最小值，还是(iou - 0.5) * 2呢？ 多谢指导了。想在我的工作里应用iou predictor。

**Comment by fereenwong** [comment]
@vacancy As mentioned in the paper, _remove from this candidate set the bounding boxes having an IoU less than Ωtrain = 0.5_, so the iou of the remained candidates will be between [0.5, 1]. So the normalize is applied to the values between the remained [0.5, 1] or the unremoved [0, 1]?
