### ISSUE TITLE
 RoI Align VS PrRoI Pooling

### ISSUE THREAD

**Issue by promach** [vacancy/PreciseRoIPooling#51]
1. Since [both use bilinear interpolation](https://towardsdatascience.com/understanding-region-of-interest-part-2-roi-align-and-roi-warp-f795196fc193), why RoI Align is **discrete** while PrRoI Pooling is **continuous** ?
2. Could anyone explain the intuition behind the derivative of PrPool()?
3. Why "The process (FC layers) after ROI pooling does not share among ROI, and takes time, which makes RPN approaches slow" ?
4. How does [position-sensitive score map](https://towardsdatascience.com/review-r-fcn-positive-sensitive-score-maps-object-detection-91cd2389345c) solve this FC layer problem in question 3 above ?

![RoI_Pooling_methods](https://user-images.githubusercontent.com/3324659/89118369-d2ec9a80-d4d7-11ea-9964-d49e0ca8bb0a.png)

![PrRoI_Pooing_derivative](https://user-images.githubusercontent.com/3324659/89118375-ded85c80-d4d7-11ea-8228-73d1f1060c37.png)

**Comment by vacancy** [comment]
> Since both use bilinear interpolation, why RoI Align is discrete while PrRoI Pooling is continuous ?

RoIAlign samples 4 points in the bounding box before bilinear interpolation. When you are talking about continuity, I assume you are talking about whether the gradient is continuous.

> Could anyone explain the intuition behind the derivative of PrPool()?
It's... kind of similar to how you take the derivative for a bilinear pooling I guess.

> Why "The process (FC layers) after ROI pooling does not share among ROI, and takes time, which makes RPN approaches slow" ?
I am not exactly sure about where did you copy this sentence... Which paper is that? It seems to me the author was saying that, in Faster RCNN, you need to run through FC layers whose input has num_images * num_roi_per_image feature maps.

> How does position-sensitive score map solve this FC layer problem in question 3 above ?
This is not related to this repo... I suggest you reading the original rfcn paper for more details...

**Comment by promach** [comment]
How does the result for the derivative of PrPool() lead to a conclusion that the gradient is continuous ?
It still have PrPool() in the expression for the derivative.

**Comment by vacancy** [comment]
Note that the computation of PrPool does not involve any sampling.
