### ISSUE TITLE
help! build error

### ISSUE THREAD

**Issue by bebebe666** [vacancy/PreciseRoIPooling#58]
Hi,
when I call the PreciseRoiPooling, and then build the library, meet some problems,

ubuntu18.04 cuda10.0 python3.6 pytorch1.1.0  gcc7 and the repo was git from the website 

the following is the building error when I enter the ninja -v in the ninja build file directory  How can I solve it，thank you

[1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/TH -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/bebebe/anaconda3/envs/pytracking2/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
FAILED: prroi_pooling_gpu_impl.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/TH -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/bebebe/anaconda3/envs/pytracking2/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu(1): error: expected a declaration

1 error detected in the compilation of "/tmp/tmpxft_00000aaf_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/TH -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/bebebe/anaconda3/envs/pytracking2/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o 
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/TH -isystem /home/bebebe/anaconda3/envs/pytracking2/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/bebebe/anaconda3/envs/pytracking2/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
In file included from /home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:19:0:
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected unqualified-id before ‘.’ token
 ../../../src/prroi_pooling_gpu_impl.cuh
 ^
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘at::Tensor prroi_pooling_backward_cuda(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float)’:
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:66:5: error: ‘PrRoIPoolingBackwardGpu’ was not declared in this scope
     PrRoIPoolingBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:66:5: note: suggested alternative: ‘prroi_pooling_backward_cuda’
     PrRoIPoolingBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~
     prroi_pooling_backward_cuda
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘at::Tensor prroi_pooling_coor_backward_cuda(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float)’:
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:97:5: error: ‘PrRoIPoolingCoorBackwardGpu’ was not declared in this scope
     PrRoIPoolingCoorBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:97:5: note: suggested alternative: ‘prroi_pooling_coor_backward_cuda’
     PrRoIPoolingCoorBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
     prroi_pooling_coor_backward_cuda
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘void pybind11_init__prroi_pooling(pybind11::module&)’:
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:110:42: error: ‘prroi_pooling_forward_cuda’ was not declared in this scope
     m.def("prroi_pooling_forward_cuda", &prroi_pooling_forward_cuda, "PRRoIPooling_forward");
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bebebe/tracking/new/new/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:110:42: note: suggested alternative: ‘prroi_pooling_backward_cuda’
     m.def("prroi_pooling_forward_cuda", &prroi_pooling_forward_cuda, "PRRoIPooling_forward");
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                          prroi_pooling_backward_cuda
ninja: build stopped: subcommand failed.

**Comment by vacancy** [comment]
Please use the `git clone` tool to download the repo.

**Comment by bebebe666** [comment]
thank you very much, I have already solve it. The problem is that the repo I use was copy from windows(use git clone to download), and it does not work. I try to git in ubuntu and then solve it! thank you

**Comment by vacancy** [comment]
Thanks for reporting. Putting up an updated note in the readme about windows git versions.
