### ISSUE TITLE
使用prpool后，后面运行停滞在全连接层

### ISSUE THREAD

**Issue by hongdayu** [vacancy/PreciseRoIPooling#6]
换回roi_align后，可以正常运行？
这个问题怎么解决呢？谢谢
@vacancy

**Comment by vacancy** [comment]
Hi @hongdayu ,

Thank you for your interest in this work.

Could you please share some minimal examples so that we can reproduce this issue? That will be extremely helpful. Thanks.

**Comment by hongdayu** [comment]
> Hi @hongdayu ,
> 
> Thank you for your interest in this work.
> 
> Could you please share some minimal examples so that we can reproduce this issue? That will be extremely helpful. Thanks.

我在https://github.com/roytseng-tw/Detectron.pytorch基础上想加上iounet。
forward是这样的：
![image](https://user-images.githubusercontent.com/32477868/46239568-ae4fa500-c3cc-11e8-8060-bf2fd1c9e81f.png)
prpool是这样调用的：
![image](https://user-images.githubusercontent.com/32477868/46239570-b60f4980-c3cc-11e8-8054-f1e0bc930c6b.png)

x = self.convs(x) 能运算，但后面就停住了，不报错也没异常，就是GPU100%运行着，成了死进程。
应该实际我的实现有问题。因为我直接将作者实现的fasterRCNN的roi_align改成prpool是可以正常运行的。
但我找不到我出错的原因，

**Comment by zzdang** [comment]
请问对于iou分支的loss,你是用的什么loss?另外iou target是predict box和gt box的iou吗?这样的话就是一个连续的值,会不会比较难收敛
Algorithm 2:optimization-based bounding bix refinement这部分是不是比较难写
老板让我复现 iou net,好慌

**Comment by vacancy** [comment]
@zzdang please refer to #5

**Comment by bozki** [comment]
你好，请问您给的这部分代码是把文件直接复制到ptyhon地下的torch文件夹嘛？
