### ISSUE TITLE
 Some questions about input and output.

### ISSUE THREAD

**Issue by A-good-kids** [vacancy/PreciseRoIPooling#61]
First of all, thank you for your outstanding contributions. I have some confusion when introducing your method into my own project. The size of my input image is 550*550, the size of the feature map is 69, 69, and the roi is tensor [1, 12, 20 , 331, 415]
roi_features = prroi_pool2d(featuremap,roi, 7,7, 1/8)
Is it correct to use this way?
Then output the result roi_shape: torch.Size([5, 256, 7, 7])
, 256*7*7 size feature, and what does this 5 mean? If you can get your answer, it will be of great help to me.

**Comment by vacancy** [comment]
ROI should be a 2-dim tensor.

Feature Map = [B, C, H, W]
ROI = [K, 5]
Output = [K, C, 7, 7]

Do not duplicate your question.

**Comment by A-good-kids** [comment]
What does k mean?

**Comment by vacancy** [comment]
Number of ROIs.
