### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by fengxiuyaun** [vacancy/PreciseRoIPooling#8]
你好，非常感谢您的分享-IOUnet，但是我有几处不了解的地方。
 1. 文章说For a better performance, we use class-aware IoU predictors.这个是什么意思呢?
2.在3.1 Learning to predict IoU节，这部分仅是介绍了怎么训练Standalone IoU-Net吧？就如rcnn一样分两步：第一步先训练前面的FPN。第二步，在您说的augment GT上训练IOU那个分支。再第二步的时候把augment的产生的box和第一步产生的feature输入到PrRoI-Pooling中，预测得到的IOU与IOU标签（取值[-1,1]）作loss，进行训练？
3.假如联合训练的话就是再2中第二步添加下边的分类和回归分支？

**Comment by fengxiuyaun** [comment]
还有就是，我还是不能理解IOU lable怎么会分布到[-1,1]。您说预测得到的iou是预测到的bounding box 与真值框的IOU，怎么会有负数呢？就如完全不匹配顶多是IOU=0呀？

**Comment by joishbader** [comment]
这应该算是专有名词吧，我翻译的也不准，如果你在搜索引擎里输入class-aware detector or class-agnostic detector，应该能获得非常详尽的解释:)

**Comment by vacancy** [comment]
On Class-aware IoU predictors.

In short, assuming we have 80 classes in our dataset, the output of the IoU prediction branch is a vector `iou` of length 80 for each bounding box. After determining its class label `c` (based on the classification branch), we use `iou[c]` as the predicted IoU.

BTW, the bounding box regression branch in Faster R-CNN/Mask R-CNN is also "class-aware".

**Comment by fengxiuyaun** [comment]
oh, thank you very much

**Comment by vacancy** [comment]
Closing this thread. Feel free to reopen it if you have any further questions.
