### ISSUE TITLE
怎样在pytorch1.0下使用？

### ISSUE THREAD

**Issue by xjtuwh** [vacancy/PreciseRoIPooling#9]
你好，我在pytorch1.0版本的环境下运行/travis.sh时提示如下错误：
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
请问怎样解决这个问题？

**Comment by xjtuwh** [comment]
好的，非常高兴收到您的回复，那我试着把*.c文件转成*.cpp文件吧。

**Comment by xjtuwh** [comment]
但是，我编程能力不好，不知道把*c文件怎样转成*.cpp文件并编译通过，希望大神多多指教~ @vacancy

**Comment by vacancy** [comment]
Resolved by 6162ad8. Use the branch pytorch1.0 instead.
